name: Deploy to Amazon S3
on:
  push:
    branches:
      - feature/docker-deploy
env:
  AWS_REGION: us-east-1
jobs:
  build:
    script:
      - npm ci
      - npm run build
    artifacts:
      paths:
        - dist/
  deploy:
    name: Deploy
    runs-on: node:22
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Sync bucket
        run: aws s3 sync dist/ s3://${{ secrets.BUCKET_NAME }} --delete
